-- DROP DATABASE IF EXISTS BAMAZON_DB;
-- Creates the database --
-- CREATE DATABASE BAMAZON_DB;
INSERT INTO `BAMAZON_DB`.`USERS` (`EMP_ID`, `USER_ID`, `NAME`, `USER_ROLE`, `PW`) 
VALUES ('495558', 'DAVEWIL', 'DAVE WILLIAMSON', 'ADMIN', '12345');

DROP TABLE BAMAZON_DB.USERS ;

CREATE TABLE BAMAZON_DB.USERS (
 EMP_ID VARCHAR(10)
,USER_ID VARCHAR(10)
,NAME VARCHAR(50)
,USER_ROLE VARCHAR(20)
,PW VARCHAR(20)
,LAST_LOGIN_DT VARCHAR(30)
,PRIMARY KEY(EMP_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE BAMAZON_DB.CUSTOMERS (
 CUST_ID INTEGER(11) NOT NULL AUTO_INCREMENT
,CUST_NAME VARCHAR(50)
,CITY VARCHAR(30)
,STATE VARCHAR(5)
,PW VARCHAR(30)
,PRIMARY KEY(CUST_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE BAMAZON_DB.PRODUCTS (
 ITEM_CD VARCHAR(20)
,PROD_NM VARCHAR(40)
,PROD_DESC VARCHAR(500)
,DEPT_ID VARCHAR(20)
,PRICE DECIMAL(10,2)
,COST DECIMAL(10,2)
,ON_HAND_QTY INTEGER
,FEATURED_FLAG BOOLEAN DEFAULT FALSE
,PRIMARY KEY(ITEM_CD)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE BAMAZON_DB.DEPARTMENTS (
DEPT_ID VARCHAR(10) NOT NULL
,DEPT_DESC VARCHAR(20)
,PRIMARY KEY(DEPT_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE BAMAZON_DB.SALES (
ORDER_ID INTEGER(11) NOT NULL AUTO_INCREMENT
,SALES_DT DATE
,CUST_ID INTEGER(11)
,ITEM_CD VARCHAR(20)
,QTY DECIMAL(10,2)
,COST DECIMAL(10,2)
,PROMO_DISC DECIMAL(10,2)
,GRAND_TOTAL DECIMAL(10,2)
,PRIMARY KEY(ORDER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE BAMAZON_DB.PROMOS (
 PROMO_CD VARCHAR(10) NOT NULL 
,PROMO_DESC VARCHAR(20)
,PROMO_AMT DECIMAL(10,2)
,PRIMARY KEY (PROMO_CD)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- QUERY FOR SALES BY DEPARTMENT
SELECT 
p.DEPT_ID
,d.DEPT_DESC
,SUM(s.GRAND_TOTAL) AS GROSS_SALES
,SUM(s.COST) AS TOTAL_COST
,SUM(s.GRAND_TOTAL)-SUM(s.COST) AS TOTAL_PROFIT

FROM BAMAZON_DB.SALES AS s

 JOIN BAMAZON_DB.PRODUCTS as p
 ON s.ITEM_CD=p.ITEM_CD

JOIN BAMAZON_DB.DEPARTMENTS AS d
ON p.DEPT_ID=d.DEPT_ID

GROUP BY 1,2